version: "3.3"

services:
  scoss_tagger:
    build: .
    volumes:
      - .:/code
    image: ngocjr/scoss_tagger
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - scoss_tagger_mongo

  scoss_tagger_mongo:
    image: 'mongo'
    container_name: 'scoss_tagger_mongodb'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: scoss
    volumes:
      - mongo_volume:/data/db
      - ./webapp/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27018:27017

volumes:
  mongo_volume:
